// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Application.Items.Dto;
//
//    var randomQuoteDto = RandomQuoteDto.FromJson(jsonString);

namespace Application.Items.Dto
{
    using System;
    using System.Text.Json.Serialization;


    public partial class RandomQuoteDto
    {
        [JsonPropertyName("quote_id")]
        public long? QuoteId { get; set; }

        [JsonPropertyName("quote")]
        public string Quote { get; set; }

        [JsonPropertyName("author")]
        public string Author { get; set; }

        [JsonPropertyName("series")]
        public string Series { get; set; }
    }

}
